name: ModdedAdditions
version: ${full.project.version}
main: xyz.fluxinc.moddedadditions.ModdedAdditions
api-version: 1.13
depend: [FluxCore, CommandAPI]
authors: [CelesteMagisteel, monoOokami]
description: Adds some cool tools/features that aren't in vanilla
commands:
  notify:
    usage: notify <name>
  moddedadditions:
    usage: moddedadditions reload
    aliases: [ma, moddeda, madditions, madd, modadd]
  voteday:
    usage: dayvote <yes/no>
    aliases: [dv, dayvote]
permissions:
  moddedadditions.*:
    description: Grants all permissions from the plugin
    children:
      moddedadditions.areatool.*: true
      moddedadditions.veinminer.*: true
      moddedadditions.give: true
      moddedadditions.give.others: true
      moddedadditions.sort: true
      moddedadditions.reload: true
      moddedadditions.spells.*: true
  moddedadditions.areatool.*:
    description: Grants all permissions for modifying areatools
    children:
      moddedadditions.areatool.add: true
      moddedadditions.areatool.remove: true
      moddedadditions.areatool.save: true
      moddedadditions.areatool.reload: true
  moddedadditions.veinminer.*:
    description: Grants all permissions for modifying veinminer
    children:
      moddedadditions.veinminer.add: true
      moddedadditions.veinminer.remove: true
      moddedadditions.veinminer.save: true
      moddedadditions.veinminer.reload: true
  moddedadditions.spells.*:
    description: Grants all spell permissions
    children:
      moddedadditions.spells.learn: true
      moddedadditions.spells.unlearn: true
      moddedadditions.spells.fillmana: true
      moddedadditions.spells.evaluate: true
      moddedadditions.spells.evaluateall: true
  moddedadditions.books.color:
    description: Allows you to use color codes in books
    default: op
  moddedadditions.veinminer.add:
    description: Add blocks to the veinminer list
    default: op
  moddedadditions.veinminer.remove:
    description: Add blocks to the veinminer list
    default: op
  moddedadditions.veinminer.save:
    description: Add blocks to the veinminer list
    default: op
  moddedadditions.veinminer.reload:
    description: Add blocks to the veinminer list
    default: op
  moddedadditions.areatool.add:
    description: Add blocks to the areatool list
    default: op
  moddedadditions.areatool.remove:
    description: Add blocks to the areatool list
    default: op
  moddedadditions.areatool.save:
    description: Add blocks to the areatool list
    default: op
  moddedadditions.areatool.reload:
    description: Add blocks to the areatool list
    default: op
  moddedadditions.reload:
    description: Reload the configurations and language file
    default: op
  moddedadditions.coloranvil.use:
    description: Allows you to color item names in an anvil
    default: op
  moddedadditions.veinminer.toggle:
    description: Toggle veinminer for yourself
    default: true
  moddedadditions.sort:
    description: Toggle chests sorting when they are opened
    default: true
  moddedadditions.give:
    description: Give custom items to yourself
    default: op
  moddedadditions.give.others:
    description: Give custom items to others
    default: op
  moddedadditions.fillmana:
    description: Fill your mana to full
    default: op
  moddedadditions.spells.learn:
    description: Learn a spell
    default: op
  moddedadditions.spells.unlearn:
    description: Learn a spell
    default: op
  moddedadditions.spells.evaluate:
    description: Evaluate a players data
    default: op
  moddedadditions.spells.evaluateall:
      description: Evaluate all player data
      default: op